version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - APP_CONFIG_REDIS_ENDPOINT=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
